spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api_tes?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

#spring:
#  datasource:
#    url: jdbc:h2:mem:testd
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect